//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class listUsers:public drogon::DrTemplate<listUsers>
{
public:
	listUsers(){};
	virtual ~listUsers(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
