//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
namespace views
{
class login:public drogon::DrTemplate<login>
{
public:
	login(){};
	virtual ~login(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
}
